---

#- name: login to registry
#  shell: "docker login -e einav.friedman@kenshoo.com -p Predator77$ -u einavf https://hub.docker.com"


#- name: pull apache docker_image
#  shell: docker pull einavf/ubuntu_apache_server:v2

#- name: pull mongodb docker_image
#  shell: docker pull einavf/mongodb:v1

#- name: run mongodb container
#  shell: docker run  -p 27017:27017 --name mongodb -d einavf/mongodb:v1

#- name: run apache2 server
#  shell:  docker run -it -d -p 80:80 --name webserver einavf/ubuntu_apache_server:v2

#- name: start apache server
#  shell: docker exec webserver /etc/init.d/apache2 start

#######################################################################
#- name: run apache container
#  docker:
#    name: webserver
#    image: "einavf/ubuntu_apache_server:v2"
#    state: restarted
#    publish_all_ports: yes

#- name: mongodb
#  docker:
#    name: mongodb
#    image: someuser/appimage
#    state: reloaded
#    pull: always
#    links:
#    - "einavf/mongodb"
#    ports:
#    - "27017:27017"

#######################################################################


#- name: add mongodb service to systemd
#   get_url:
#     url=  https://s3.us-east-2.amazonaws.com/docker-services-test/mongodb.service
#     dest= /etc/systemd/system/mongodb.service
#     mode=0755



# - name: add apache-web-server as a service to systemd
#   become: yes
#   get_url:
#     url=  https://s3.us-east-2.amazonaws.com/docker-services-test/webserver.service
#     dest= /etc/systemd/system/webserver.service
#     mode=0755

# - name: start the mongodb service
#   become: yes
#   shell: systemctl enable mongodb  
#   shell: systemctl daemon-reload  
#   shell: systemctl start mongodb  

# - name: start the apache-web-server service
#   become: yes
#   shell: systemctl enable webserver  
#   shell: systemctl daemon-reload  
#   shell: systemctl start webserver  
